### ISSUE TITLE
Used with pointcloud 2.0

### ISSUE THREAD

**Issue by daviddc86** [petrbroz/forge-potree-demo#3]
Hello
I need some help.
I am trying to add the pointlcoud 2.0's to a project with AutoDesk Forge Viewer that uses THREE 71.

I read the files well but the material is different for the THREE version and I get a figure with triangles and many blanks.

![Capture](https://user-images.githubusercontent.com/4498677/121237567-785e6080-c897-11eb-8531-f0cb720a0f84.JPG)

**Comment by petrbroz** [comment]
Hi David,

The modified version of Potree used in this sample app (available under [public/scripts/potree](https://github.com/petrbroz/forge-potree-demo/tree/master/public/scripts/potree)) is based on an older version of Potree, I think it was 1.6 or 1.7. Point cloud data generated with Potree version 2.0 will most likely be incompatible with our version. At the moment we're not planning to back-port another version of Potree, so if you'd like to bring your point cloud data to Forge Viewer, I'd suggest that you use the format version 1.6 or 1.7.
