### ISSUE TITLE
Potree point cloud is not showing

### ISSUE THREAD

**Issue by javrro** [petrbroz/forge-potree-demo#5]
Ive ran the project as is, without any modification but im unable to see the Point Cloud.

**Comment by leefsmp** [comment]
+1

**Comment by petrbroz** [comment]
Hi, sorry about that. Some time back the viewer switched from WebGL to WebGL2, and the Potree renderer seems to be having some issues with the newer version. For now, you can work around this issue by configuring the viewer to go back to WebGL(1), like so:

```js
viewer.start(null, null, null, null, {
    webglInitParams: {
        useWebGL2: false
    }
});
```

I've updated the sample to do this as well.
